name: 🚀 Automated Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.2)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: 📥 Checkout Source Code
      uses: actions/checkout@v4
      
    - name: 📥 Checkout Releases Repository
      uses: actions/checkout@v4
      with:
        repository: bilalmohib/aussie-vault-browser-releases
        path: ../aussie-vault-browser-releases
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 📥 Checkout Homebrew Tap
      uses: actions/checkout@v4
      with:
        repository: bilalmohib/homebrew-aussievault
        path: ../homebrew-aussievault
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install Dependencies
      run: npm ci
      
    - name: 🏗️ Build Application
      run: npm run make
      
    - name: 🚀 Run Release Script
      run: ./scripts/publish-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: ✅ Release Summary
      run: |
        echo "🎉 Release completed successfully!"
        echo "📦 Version: ${{ github.event.inputs.version || github.ref_name }}"
        echo "🔗 Check releases: https://github.com/bilalmohib/aussie-vault-browser-releases/releases" 